Aydın için ekleme yapıldı.
acikkaynak/calisma-mekanlari pull request #40
Opened 2023-08-05 16:28 UTC by alicangunduz

Aydın ili için ekleme yapıldı.

2023-08-07 06:43 UTC, ramazansancar requested changes
Gereken düzenleme talebi not düşülmüştür.

2023-08-07 06:43 UTC, ramazansancar commented on README.md
> +| Efeler  | Daniels Coffee  | N/A         | Çalışma salonunda her masada mevcut          | Mevcut | 500 Mbps   | 5/10                     | 10:00 - 22:00    | @danielscoffee.aydin           | N/A
Harita konumu olarak bu adresi ekleyebiliriz.

https://goo.gl/maps/C6Nvdfch3BP5hnPA6

Haritalardan kontrol ettiğimde çalışma saatleri 10.00-00.00 şeklinde yazılmış. Burada da düzeltme yapılması faydalı olacaktır. (Gerekirse Instagram sayfasına mesaj atılarak teyit edilebilir)

2023-08-07 08:15 UTC, flightlesstux approved these changes

2023-08-07 08:15 UTC, flightlesstux commented
@ramazansancar another conflict here. could you fix it, please?

2023-08-07 09:17 UTC, ramazansancar commented
> @ramazansancar another conflict here. could you fix it, please?

I cannot make changes because I am not authorized. I contacted "Ramazansancar#0" on discord regarding authorization.

2023-08-07 09:52 UTC, alicangunduz commented on README.md
> +| Efeler  | Daniels Coffee  | N/A         | Çalışma salonunda her masada mevcut          | Mevcut | 500 Mbps   | 5/10                     | 10:00 - 22:00    | @danielscoffee.aydin           | N/A
Harita konumunu ekleyeceğim , işletmeden direkt bilgi 22.00 için bu süre sanırım üniversite dönemleri genişletilebiliniyor ama bilgilendirmeleri 22.00 üzerineydi

2023-08-07 11:25 UTC, alicangunduz commented
@ramazansancar ilgili düzenleme yapıldı.

2023-08-07 11:35 UTC, ramazansancar approved these changes
Thanks

2023-08-07 11:38 UTC, ramazansancar approved these changes

2023-08-07 11:38 UTC, ramazansancar commented on README.md
> +| Efeler  | Daniels Coffee  | N/A         | Çalışma salonunda her masada mevcut          | Mevcut | 500 Mbps   | 5/10                     | 10:00 - 22:00    | @danielscoffee.aydin           | N/A
Teşekkürler, haritalarda öyle görünce acaba hatalı mı diye düşündüğüm için o şekilde not düşmüştüm.

2023-08-11 03:12 UTC, alicangunduz commented
@ramazansancar  Is there anything else I should do?

2023-08-11 06:25 UTC, ramazansancar commented
> @ramazansancar Is there anything else I should do?

Conflicts need to be resolved in order to merge. @alicangunduz 
I couldn't figure it out because he doesn't have the authority to edit your repo. :(

2023-08-25 13:18 UTC, merged